name: Build APK

on: push:
  branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant executable permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew :app:assembleDebug

      - name: List APK directory
        run: ls -R app/build/outputs/apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/**/*.apk
